services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - walletzk-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'walletzk']
      interval: 5s
      timeout: 10s
      retries: 5

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:${MAIL_CLIENT_PORT}
      - ${MAIL_PORT}:${MAIL_PORT}

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}

  zkwallet-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zkwallet-api
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx-webserver
    restart: unless-stopped
    environment:
      - ${CERTBOT_EMAIL}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - nginx:/etc/letsencrypt
      - ./nginx-conf:/etc/nginx/user_conf.d
    depends_on:
      - zkwallet-api

volumes:
  walletzk-db:
  nginx:
