services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - walletzk-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - walletzk
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'walletzk']
      interval: 5s
      timeout: 10s
      retries: 5

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
    networks:
      - walletzk

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - walletzk

  # Uncomment to use redis
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - 6379:6379

  zkwallet-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zkwallet-api
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - walletzk
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  nginx-webserver:
    image: nginx:mainline-alpine
    container_name: nginx-webserver
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - zkwallet-api
    networks:
      - walletzk

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx-webserver
    networks:
      - walletzk
    command: certonly --webroot --webroot-path=/var/www/html --email hello@walletzk.app --agree-tos --no-eff-email --staging -d api.walletzk.app

volumes:
  walletzk-db:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/zkwallet/zkwallet-api/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/zkwallet/zkwallet-api/dhparam/
      o: bind

networks:
  walletzk:
